#!/bin/bash

# Replace the old deployment files with the new ones
rm -rf /home/ec2-user/backend-deployment
cp -r /home/ec2-user/codedeploy-landingpad/back/ /home/ec2-user/backend-deployment

cd /home/ec2-user/backend-deployment
npm install
node index.js